import type { Metadata } from "next";
import { BookBanner } from "@/widgets/bookBanner/bookBanner";

export const metadata: Metadata = {
  title: "Hengeler's Hof",
  description: "Generated by create next app"
};

export default async function ImageHeaderLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <BookBanner />
      {children}
    </>
  );
}
